name: Secret Scan

on:
  pull_request:
    branches: [develop]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Grep for AWS keys and password-like strings
        working-directory: /front-web-site-for-riften-terraform/riften_web_infra/terraform
        run: |
          set -e
          # AWS Access Key
          if grep -rE 'AKIA[0-9A-Z]{16}' .; then
            echo "Error: AWS Access Key detected" >&2; exit 1; fi
          # AWS Secret Key
          if grep -rE '([A-Za-z0-9/+=]{40})' . | grep -i 'secret'; then
            echo "Error: AWS Secret Key detected" >&2; exit 1; fi
          # password-like
          if grep -rEi 'password\s*[=:]\s*.+|pwd\s*[=:]\s*.+|pass\s*[=:]\s*.+|passwd\s*[=:]\s*.+|パスワード\s*[=:]\s*.+|secret\s*[=:]\s*.+|token\s*[=:]\s*.+|api[_-]?key\s*[=:]\s*.+|client[_-]?secret\s*[=:]\s*.+|access[_-]?key\s*[=:]\s*.+|aws[_-]?secret' .; then
            echo "Error: Password-like string detected" >&2; exit 1; fi
