name: Secret Scan

on:
  pull_request:
    branches: [develop]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grep for AWS keys and password-like strings
        working-directory: riften_web_infra/terraform
        run: |
          set -e
          echo "[INFO] Start AWS Access Key scan"
          result=$(grep -rE 'AKIA[0-9A-Z]{16}' . || true)
          if [ -n "$result" ]; then
            echo "$result" >&2
            echo "[ERROR] AWS Access Key detected" >&2; exit 1;
          else
            echo "[INFO] No AWS Access Key found"
          fi
          echo "[INFO] Start password-like string scan"
          result=$(grep -rEi 'password\s*[=:]\s*.+|pwd\s*[=:]\s*.+|pass\s*[=:]\s*.+|passwd\s*[=:]\s*.+|パスワード\s*[=:]\s*.+|secret\s*[=:]\s*.+|token\s*[=:]\s*.+|client[_-]?secret\s*[=:]\s*.+|access[_-]?key\s*[=:]\s*.+' . || true)
          if [ -n "$result" ]; then
            echo "$result" >&2
            echo "[ERROR] Password-like string detected" >&2; exit 1;
          else
            echo "[INFO] No password-like string found"
          fi
